// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Part struct {
	PartID      uuid.UUID      `json:"part_id"`
	Skill       string         `json:"skill"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Sequence    int32          `json:"sequence"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Question struct {
	QuestionID           uuid.UUID      `json:"question_id"`
	QuestionGroupID      uuid.NullUUID  `json:"question_group_id"`
	QuestionOrder        int32          `json:"question_order"`
	TextContent          sql.NullString `json:"text_content"`
	AudioUrl             sql.NullString `json:"audio_url"`
	ImageUrl             sql.NullString `json:"image_url"`
	ExpectedAnswerFormat sql.NullString `json:"expected_answer_format"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type QuestionGroup struct {
	QuestionGroupID    uuid.UUID      `json:"question_group_id"`
	Name               string         `json:"name"`
	Description        sql.NullString `json:"description"`
	ContextTextContent sql.NullString `json:"context_text_content"`
	ContextAudioUrl    sql.NullString `json:"context_audio_url"`
	ContextImageUrl    sql.NullString `json:"context_image_url"`
	PartID             uuid.UUID      `json:"part_id"`
	GroupType          string         `json:"group_type"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	PlanType           string         `json:"plan_type"`
	Version            int32          `json:"version"`
	IsLocked           sql.NullBool   `json:"is_locked"`
	LockedAt           sql.NullTime   `json:"locked_at"`
	LockReason         sql.NullString `json:"lock_reason"`
	UnlockedAt         sql.NullTime   `json:"unlocked_at"`
	UnlockReason       sql.NullString `json:"unlock_reason"`
}

type QuestionOption struct {
	OptionID        uuid.UUID    `json:"option_id"`
	QuestionID      uuid.UUID    `json:"question_id"`
	OptionName      string       `json:"option_name"`
	OptionValue     string       `json:"option_value"`
	IsCorrectOption sql.NullBool `json:"is_correct_option"`
	CreatedAt       sql.NullTime `json:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	UserName      string         `json:"user_name"`
	Email         string         `json:"email"`
	Password      string         `json:"password"`
	IsSocialLogin sql.NullBool   `json:"is_social_login"`
	IsLocked      sql.NullBool   `json:"is_locked"`
	LockedAt      sql.NullTime   `json:"locked_at"`
	LockReason    sql.NullString `json:"lock_reason"`
	UnlockedAt    sql.NullTime   `json:"unlocked_at"`
	UnlockReason  sql.NullString `json:"unlock_reason"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type UserProfile struct {
	UserID      uuid.UUID      `json:"user_id"`
	FullName    sql.NullString `json:"full_name"`
	Birthday    sql.NullTime   `json:"birthday"`
	Gender      sql.NullString `json:"gender"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Address     sql.NullString `json:"address"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Bio         sql.NullString `json:"bio"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type UserProvider struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Provider       string         `json:"provider"`
	ProviderUserID string         `json:"provider_user_id"`
	Email          sql.NullString `json:"email"`
	AccessToken    sql.NullString `json:"access_token"`
	RefreshToken   sql.NullString `json:"refresh_token"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	FullName       sql.NullString `json:"full_name"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
