// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Exam struct {
	ExamID            uuid.UUID      `json:"exam_id"`
	ExamTitle         string         `json:"exam_title"`
	Description       sql.NullString `json:"description"`
	DurationMinutes   sql.NullInt32  `json:"duration_minutes"`
	ExamType          string         `json:"exam_type"`
	MaxListeningScore sql.NullInt32  `json:"max_listening_score"`
	MaxReadingScore   sql.NullInt32  `json:"max_reading_score"`
	MaxSpeakingScore  sql.NullInt32  `json:"max_speaking_score"`
	MaxWritingScore   sql.NullInt32  `json:"max_writing_score"`
	TotalScore        sql.NullInt32  `json:"total_score"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type ExamPart struct {
	PartID              uuid.UUID      `json:"part_id"`
	ExamID              uuid.NullUUID  `json:"exam_id"`
	PartTitle           string         `json:"part_title"`
	PartOrder           sql.NullInt32  `json:"part_order"`
	Description         sql.NullString `json:"description"`
	IsPracticeComponent sql.NullBool   `json:"is_practice_component"`
	PlanType            string         `json:"plan_type"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	ToeicPartNumber     sql.NullInt32  `json:"toeic_part_number"`
}

type Paragraph struct {
	ParagraphID      uuid.UUID      `json:"paragraph_id"`
	ParagraphContent string         `json:"paragraph_content"`
	Title            sql.NullString `json:"title"`
	PartID           uuid.UUID      `json:"part_id"`
	ParagraphOrder   int32          `json:"paragraph_order"`
	ParagraphType    sql.NullString `json:"paragraph_type"`
	AudioUrl         sql.NullString `json:"audio_url"`
	ImageUrl         sql.NullString `json:"image_url"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Question struct {
	QuestionID           uuid.UUID             `json:"question_id"`
	QuestionContent      string                `json:"question_content"`
	QuestionType         string                `json:"question_type"`
	PartID               uuid.UUID             `json:"part_id"`
	ParagraphID          uuid.NullUUID         `json:"paragraph_id"`
	QuestionOrder        int32                 `json:"question_order"`
	AudioUrl             sql.NullString        `json:"audio_url"`
	ImageUrl             sql.NullString        `json:"image_url"`
	ToeicQuestionSection string                `json:"toeic_question_section"`
	QuestionNumberInPart sql.NullInt32         `json:"question_number_in_part"`
	AnswerOption         pqtype.NullRawMessage `json:"answer_option"`
	CorrectAnswer        sql.NullString        `json:"correct_answer"`
	CreatedAt            sql.NullTime          `json:"created_at"`
	UpdatedAt            sql.NullTime          `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	UserName      string         `json:"user_name"`
	Email         string         `json:"email"`
	Password      string         `json:"password"`
	IsSocialLogin sql.NullBool   `json:"is_social_login"`
	IsLocked      sql.NullBool   `json:"is_locked"`
	LockedAt      sql.NullTime   `json:"locked_at"`
	LockReason    sql.NullString `json:"lock_reason"`
	UnlockedAt    sql.NullTime   `json:"unlocked_at"`
	UnlockReason  sql.NullString `json:"unlock_reason"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type UserProfile struct {
	UserID      uuid.UUID      `json:"user_id"`
	FullName    sql.NullString `json:"full_name"`
	Birthday    sql.NullTime   `json:"birthday"`
	Gender      sql.NullString `json:"gender"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Address     sql.NullString `json:"address"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Bio         sql.NullString `json:"bio"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type UserProvider struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Provider       string         `json:"provider"`
	ProviderUserID string         `json:"provider_user_id"`
	Email          sql.NullString `json:"email"`
	AccessToken    sql.NullString `json:"access_token"`
	RefreshToken   sql.NullString `json:"refresh_token"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	FullName       sql.NullString `json:"full_name"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
