// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	// AssignPermissionToRole assigns a permission to a role.
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	// AssignRoleToUser assigns a role to a user.
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	// CreateAccount creates a new user and returns selected fields.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	// ========================
	// 002
	// ========================
	CreatePart(ctx context.Context, arg CreatePartParams) error
	// CreatePermission creates a new permission.
	CreatePermission(ctx context.Context, arg CreatePermissionParams) error
	CreateQuestionGroup(ctx context.Context, arg CreateQuestionGroupParams) (uuid.UUID, error)
	// CreateRole creates a new role.
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	// 00002
	// CreateUserProfile creates a new Userprofile.
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error
	// DeletePermission deletes a permission by its ID.
	DeletePermission(ctx context.Context, id uuid.UUID) error
	// DeleteRole deletes a role by its ID.
	DeleteRole(ctx context.Context, id uuid.UUID) error
	GetPaginatedParts(ctx context.Context, arg GetPaginatedPartsParams) ([]Part, error)
	// GetPaginatedUsers retrieves a list of users with pagination.
	GetPaginatedUsers(ctx context.Context, arg GetPaginatedUsersParams) ([]GetPaginatedUsersRow, error)
	GetPart(ctx context.Context, partID uuid.UUID) (Part, error)
	GetPartsCount(ctx context.Context) (int64, error)
	// GetPermissions retrieves all permissions.
	GetPermissions(ctx context.Context) ([]Permission, error)
	// GetRoles retrieves all roles.
	GetRoles(ctx context.Context) ([]Role, error)
	GetUserAvatar(ctx context.Context, userID uuid.UUID) (sql.NullString, error)
	// GetUserByEmailOrUserNameOrId retrieves a user by email, user_name, or id.
	GetUserByEmailOrUserNameOrId(ctx context.Context, arg GetUserByEmailOrUserNameOrIdParams) (GetUserByEmailOrUserNameOrIdRow, error)
	GetUserProfile(ctx context.Context, userID uuid.UUID) (GetUserProfileRow, error)
	// GetUsersCount returns the total number of users.
	GetUsersCount(ctx context.Context) (int64, error)
	// HasPermission checks if a user has a specific permission.
	HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error)
	// LockUser to lock user account
	LockUser(ctx context.Context, arg LockUserParams) (sql.Result, error)
	// PermissionExists checks if a permission with the given ID exists.
	PermissionExists(ctx context.Context, id uuid.UUID) (bool, error)
	// RoleExists checks if a role with the given ID exists.
	RoleExists(ctx context.Context, id uuid.UUID) (bool, error)
	// UnlockUser to unlock user account
	UnlockUser(ctx context.Context, arg UnlockUserParams) (sql.Result, error)
	UpdateAudioContentQuestionGroup(ctx context.Context, arg UpdateAudioContentQuestionGroupParams) error
	UpdateImageContentQuestionGroup(ctx context.Context, arg UpdateImageContentQuestionGroupParams) error
	UpdatePart(ctx context.Context, arg UpdatePartParams) error
	// UpdatePassword updates the password for a given user ID.
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (sql.Result, error)
	UpdateQuestionGroup(ctx context.Context, arg UpdateQuestionGroupParams) error
	UpdateTextContentQuestionGroup(ctx context.Context, arg UpdateTextContentQuestionGroupParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
